### ISSUE TITLE
New DELAY_ON_EMPTY functionality on FronteraScheduler terminates crawl right at start

### ISSUE THREAD

**Issue by plafl** [scrapinghub/frontera#33] opened 2015-04-16 15:24 UTC
While this is solved you can use this on your settings as a workaround:

    DELAY_ON_EMPTY=0.0

The problem is in `frontera.contrib.scrapy.schedulers.FrontieraScheduler`, method `_get_next_requests`.
If there are no pending requests and the test `self._delay_next_call < time()` fails, an empty list is returned which causes the crawl to terminate

**Comment by sibiryakov** [comment] 2015-04-20 15:50
Hey @plafl what's the status of this? Is it about backend returning zero results?

**Comment by plafl** [comment] 2015-04-20 21:06
@sibiryakov The problem is not that the backend does not return zero results. The problem is that the backend is not even called by FrontierScheduler. Because the backend is not called FrontierScheduler returns an empty list. Reverting to the old implementation of the method which always calls the backend if there are not pending requests would fix it, but then I will eliminate the functionality intended by _delay_next_call

**Comment by sibiryakov** [comment] 2015-04-21 07:29
I think we can find solution. How to reproduce that?

**Comment by plafl** [comment] 2015-04-21 07:44
1. Fetch this example:

        git clone https://github.com/scrapinghub/tutorials.git
        cd blog/hn_scrapper
    
2. Comment out line 5 of file `hn_scrapper/frontier_settings.py`:

        #DELAY_ON_EMPTY = 0.0

3. Launch spider:

        scrapy crawl HackerNews

**Comment by sibiryakov** [comment] 2015-04-21 08:43
This is a complex problem.

We faced with two problems here:
- Control of the finishing condition,
- Frontera scheduler willingness to fill the queue as fast and as full as possible, minimizing amount of calls to backend.

Here is what's happening in your spider+Scrapy+Frontera mix:
  1. Clean up of Frontera backend DB.
  1. First it asks Frontera backend if theres is something to download, gets zero results (because seeds aren't in db yet),
  1. Then it adds seeds (this is Scrapy engine behavior: first check next_request, if there is nothing then check start_urls)
  1. Exits, because of unsuccessful attempt to fill the queue in full at step 2.

By changing ```DELAY_ON_EMPTY``` to ```0.0``` you change Frontera's scheduler behavior, now it's allowed to ask for new requests as often as Scrapy needs at the price of hitting backend on every processed request (probably you don't care in this case).

You can follow and test all these observations by turning on logging in ```frontera_settings.py```:
 ```
LOGGING_EVENTS_ENABLED = True
LOGGING_MANAGER_ENABLED = True
LOGGING_BACKEND_ENABLED = True
LOGGING_DEBUGGING_ENABLED = False
```

**Comment by sibiryakov** [comment] 2015-04-21 08:46
Although, ```DELAY_ON_EMPTY=0.0``` solves the problem, it doesn't means that there is a bug somewhere. Another way to solve this problem is to add handling of ```spider_idle``` signal.
```Python
   # stable branch
    def set_crawler(self, crawler):
        super(HackernewsSpider, self).set_crawler(crawler)
        self.crawler.signals.connect(self.spider_idle, signal=signals.spider_idle)

    # master latest changes
    @classmethod
    def from_crawler(cls, crawler, *args, **kwargs):
        spider = cls(*args, **kwargs)
        spider._set_crawler(crawler)
        spider.crawler.signals.connect(spider.spider_idle, signal=signals.spider_idle)
        return spider

    def spider_idle(self):
        self.log("Spider idle signal caught.")
        raise DontCloseSpider
```

**Comment by sibiryakov** [comment] 2015-04-21 09:09
The main question here: how finishing condition should look like?
Now, managing of finishing condition is spread somewhere between Scrapy, Frontera and spider.

**Comment by sibiryakov** [comment] 2015-04-22 08:49
I'm working on fix now. Scrapy example in master is also affected.

**Comment by kalessin** [comment] 2015-04-24 01:57
I understand this fix is simple https://github.com/scrapinghub/frontera/pull/35 but forces the user to be very aware of internal algorithms in order to use it correctly. What if we think in a more automatic behavior, i.e. optionally backend dependant? for example instead of this line:

https://github.com/scrapinghub/frontera/blob/master/frontera/contrib/scrapy/schedulers/frontier.py#L84

```
self._delay_on_empty = self.frontier.manager.settings.get('DELAY_ON_EMPTY')
```

we could have something like:

```
default_delay_on_empty = self.frontier.manager.settings.get('DELAY_ON_EMPTY')
self._delay_on_empty = getattr(self.frontier.backend, 'delay_on_empty', default_delay_onn_empty)
```

This would allow to configure backends in an optimal way without need for the user to cope with obscure algorithm parameters.

**Comment by sibiryakov** [comment] 2015-04-24 08:02
What's the intention here? To simplify Frontera setup or avoid unexpected crawler process finishing? 

If first one, I think this wouldn't help much, because calls to get_next_requests in SQLAlchemy backend are expensive when DB becomes relatively large, for many websites (say up to 100K pages) it works fine with default setting. So if you want to crawl large amount of pages with SQLAlchemy you still need to tune this setting. Memory backend isn't considered, because it's mainly used for testing. Backends from distributed branch: HBase, Kafka, has also expensive calls. HCF is backed by HBase as I know.

About second one, this is connected to delay on empty queue mechanism by chance. Logic of when to close the crawling process is spread between Scrapy, Frontera scheduler, and spider. This area wasn't explored much before. Personally, I think this should be a part of crawling strategy. In Frontera crawling strategy is managed in backend and in spider partially. I would put the finishing condition in backend, allowing it to tell the crawler when crawling is finished and process can be stopped. At the same time leave an option for spider to force the finishing of process by reaching time limit, or getting some signal via HTTP REST api, or allowing it to do not close process at all. Therefore, extracting finishing logic from Scrapy almost completely. Just to recap:
- Backend gives a hint to Scrapy that crawling target is accomplished, it could be a general high-level decision, based on content or link structure analysis.
- Spider is responsible for managerial work, performs actual stopping by some external event.
- Scrapy isn't checking the queue for emptiness, delegating it to backend. Continues to provide handling for OS signals just as now, and other finishing mechanisms common for Scrapy.

**Comment by kalessin** [comment] 2015-04-24 18:16
This is not just a scraping strategy. It is a problem of design. We have projects that has spiders that consumes from HCF and spiders that are seed with a starting request. If we don't set DELAY_ON_EMPTY to 0, the second ones does not work, because of the logic of the scrapy scheduler (first runs next_request(), then runs add_seed(), then adds next_request() recurrently, but only if has passed a minimal time, regulated by DELAY_ON_EMPTY)

If the DELAY_ON_EMPTY is greater than 0, then the second next_request() will never run, while the first one didn't retrieve any request. So the spider stops, even if add_seeds() added the start request to the queue. That is why not consumer spiders does not work unless you set that value to 0.0.

But that forces us to use ALWAYS that value, because it is set by project, not spider. We don't have a way to configure consumer spiders with a positive value and not consumer spiders with 0.

That can be, however, easily decided by the backend, which knows whether it was configured as consumer or not.

**Comment by sibiryakov** [comment] 2015-04-24 19:43
What I was talking about is setting DELAY_ON_EMPTY isn't the only way to solve this problem. Moreover, it's affecting unexpected finishing by chance. I'm offering to remove finishing condition from Scrapy, and delegate it to backend and spider as much as possible. @kalessin you should get a mail about this also in mailing list.

**Comment by sibiryakov** [comment] 2015-12-16 10:38
With latest master changes (backend take up) and event loop halting fix in Scrapy this problem should be fixed. Anyone here to test it?

**Comment by sibiryakov** [comment] 2016-01-18 10:18
With latest Scrapy 1.0.4 and frontera 0.4.0 it should be fixed, please reopen if you find any problems.

**Closed by sibiryakov** 2016-01-18 10:18 UTC
Labels: bug
